### ISSUE TITLE
CMS 5 developer doc and user help doc are set up

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/developer-docs#44]
# Acceptance criteria
- [x] CMS 5 branches are set up for user doc and developer doc
- [x] CMS 5 content can be seen on developer doc and user doc and API doc.
- [x] CMS 5 content is clearly marked as "pre-release"
- [x] There's a clear demarcation between CMS4 and CMS5 doc.
- [x] Until CMS5 is stable, the docs default to 4
- ~~CMS 3 content no longer shows up on doc site and API Doc.~~

# Notes 
- Will probably need some UX/design feedback

## PRs
- https://github.com/silverstripe/developer-docs/pull/47
- https://github.com/silverstripe/silverstripe-userhelp-content/pull/175
- https://github.com/silverstripe/doc.silverstripe.org/pull/244
- https://github.com/silverstripe/api.silverstripe.org/pull/102

**Comment by maxime-rainville** [comment]
@silverstripe/core-team Do you have any views on removing the CMS3 doc? It's been EOL for close to a year now.

At the very least, if we keep it there, we should call attention to the fact that it's no longer supported

**Comment by emteknetnz** [comment]
I think it's worth keeping because the cost of doing so is very low and there will be some projects that simply never update.  There should be a very clear UX piece such as a big red warning in the header, and make it very easy to find your way to the 5/4 docs.  

We should also ensure that search engines no longer index the content, and while we're at it we should have something in place to push live to no longer index 4 content once 5 goes stable

**Comment by GuySartorelli** [comment]
Instead of simply not indexing the content, would it make more sense to only show results for the version you're currently viewing? So looking at V4 you see V4 results, looking at v5 you see v5 results etc

**Comment by emteknetnz** [comment]
Not index means tell google to not index it in google search.  That way people won't land on v3 results from google search.

**Comment by GuySartorelli** [comment]
Ahh, I thought you meant the search on the site itself. Yup, that's fair.

**Comment by emteknetnz** [comment]
> Instead of simply not indexing the content, would it make more sense to only show results for the version you're currently viewing? So looking at V4 you see V4 results, looking at v5 you see v5 results etc

Yeah in the search on site context that probably makes sense

**Comment by GuySartorelli** [comment]
Updating the userhelp doc sources assumes the following branches are created:
- https://github.com/symbiote/silverstripe-advancedworkflow
  branch: 6
- https://github.com/silverstripe/silverstripe-registry
  branch: 3          
- https://github.com/silverstripe/silverstripe-contentreview
  branch: 5          
- https://github.com/silverstripe/silverstripe-blog          
  branch: 4
- https://github.com/silverstripe/silverstripe-userforms          
  branch: 6
- https://github.com/silverstripe/silverstripe-subsites
  branch: 3          
- https://github.com/silverstripe/silverstripe-taxonomy
  branch: 3
- https://github.com/silverstripe/silverstripe-iframe          
  branch: 3
- https://github.com/silverstripe/silverstripe-versionfeed
  branch: 3        
- https://github.com/dnadesign/silverstripe-elemental          
  branch: 5
- https://github.com/bringyourownideas/silverstripe-maintenance        
  branch: 3
- https://github.com/silverstripe/silverstripe-sharedraftcontent          
  branch: 3
- https://github.com/silverstripe/silverstripe-documentconverter
  branch: 3
- https://github.com/silverstripe/silverstripe-ckan-registry          
  branch: 2
- https://github.com/silverstripe/silverstripe-mfa
  branch: 5
- https://github.com/silverstripe/silverstripe-securityreport          
  branch: 3
- https://github.com/silverstripe/silverstripe-sitewidecontent-report
  branch: 4
- https://github.com/silverstripe/silverstripe-session-manager
  branch: 2

**Comment by GuySartorelli** [comment]
Since there hasn't been much feedback about whether to keep CMS3 docs, I'm opting to keep them. There are still projects out there using it, its not an uncommon practice for docs of EOL versions to remain for other products, and the maintenance cost of leaving it there is basically zero.

**Comment by madmatt** [comment]
Rather than remove them, can we make it very clear that the version is EOL? Often docs include warning messages at the top of every page for versions that are no longer actively maintained or are EOL.

For example: [Elastic docs](https://www.elastic.co/guide/en/elasticsearch/reference/8.2/index.html)

**Comment by GuySartorelli** [comment]
Yup. As part of the "there's a clear demarcation between CMS4 and CMS5 doc" acceptance criteria I'm also taking this a step further, so that EOL and pre-stable version are clearly highlighted.

The current UX mockups for this have a clear banner at the top of each page (just above the h1 for that page's docs) with the version number and whether it's supported/end of life/pre-stable.
For eol/pre-stable there will be a link to the current stable docs.

**Comment by GuySartorelli** [comment]
Deployment of api.silverstripe.org is all that remains.

**Comment by GuySartorelli** [comment]
api.silverstripe.org deployed.
Cron will run overnight which will update the `5` content to be using the correct branches.
